const POSITION_MAP = {
    0: "QB",
    1: "TQB",
    2: "RB",
    3: "RB/WR",
    4: "WR",
    5: "WR/TE",
    6: "TE",
    7: "OP",
    8: "DT",
    9: "DE",
    10: "LB",
    11: "DL",
    12: "CB",
    13: "S",
    14: "DB",
    15: "DP",
    16: "D/ST",
    17: "K",
    18: "P",
    19: "HC",
    20: "BE",
    21: "IR",
    22: "",
    23: "RB/WR/TE",
    24: "ER",
    25: "Rookie",
    QB: 0,
    RB: 2,
    WR: 4,
    TE: 6,
    "D/ST": 16,
    K: 17,
    FLEX: 23,
    DT: 8,
    DE: 9,
    LB: 10,
    DL: 11,
    CB: 12,
    S: 13,
    DB: 14,
    DP: 15,
    HC: 19
};

const PRO_TEAM_MAP = {
    0: "None",
    1: "ATL",
    2: "BUF",
    3: "CHI",
    4: "CIN",
    5: "CLE",
    6: "DAL",
    7: "DEN",
    8: "DET",
    9: "GB",
    10: "TEN",
    11: "IND",
    12: "KC",
    13: "LV",
    14: "LAR",
    15: "MIA",
    16: "MIN",
    17: "NE",
    18: "NO",
    19: "NYG",
    20: "NYJ",
    21: "PHI",
    22: "ARI",
    23: "PIT",
    24: "LAC",
    25: "SF",
    26: "SEA",
    27: "TB",
    28: "WSH",
    29: "CAR",
    30: "JAX",
    33: "BAL",
    34: "HOU"
};

const ACTIVITY_MAP = {
    178: "FA ADDED",
    180: "WAIVER ADDED",
    179: "DROPPED",
    181: "DROPPED",
    239: "DROPPED",
    244: "TRADED",
    FA: 178,
    WAIVER: 180,
    TRADED: 244
};

const PLAYER_STATS_MAP = {
    0: "passingAttempts",
    1: "passingCompletions",
    2: "passingIncompletions",
    3: "passingYards",
    4: "passingTouchdowns",
    15: "passing40PlusYardTD",
    16: "passing50PlusYardTD",
    17: "passing300To399YardGame",
    18: "passing400PlusYardGame",
    19: "passing2PtConversions",
    20: "passingInterceptions",
    21: "passingCompletionPercentage",
    22: "passingYards", // Potential duplicate with 3
    23: "rushingAttempts",
    24: "rushingYards",
    25: "rushingTouchdowns",
    26: "rushing2PtConversions",
    35: "rushing40PlusYardTD",
    36: "rushing50PlusYardTD",
    37: "rushing100To199YardGame",
    38: "rushing200PlusYardGame",
    39: "rushingYardsPerAttempt",
    40: "rushingYards", // Potential duplicate with 24
    41: "receivingReceptions",
    42: "receivingYards",
    43: "receivingTouchdowns",
    44: "receiving2PtConversions",
    45: "receiving40PlusYardTD",
    46: "receiving50PlusYardTD",
    56: "receiving100To199YardGame",
    57: "receiving200PlusYardGame",
    58: "receivingTargets",
    63: "fumbleRecoveredForTD",
    64: "passingTimesSacked",
    68: "fumbles",
    72: "lostFumbles",
    89: "defensive0PointsAllowed",
    94: "defensiveTouchdowns",
    95: "defensiveInterceptions",
    96: "defensiveFumbles",
    97: "defensiveBlockedKicks",
    98: "defensiveSafeties",
    99: "defensiveSacks",
    120: "defensivePointsAllowed",
    127: "defensiveYardsAllowed",
    138: "netPunts",
    139: "puntYards",
    140: "puntsInsideThe10",
    141: "puntsInsideThe20",
    155: "teamWin",
    156: "teamLoss",
    157: "teamTie",
    201: "madeFieldGoalsFrom60Plus",
    205: "defensive2PtReturns"
};

const SETTINGS_SCORING_FORMAT_MAP = {
    0: { abbr: "PA", label: "Each Pass Attempted" },
    1: { abbr: "PC", label: "Each Pass Completed" },
    2: { abbr: "INC", label: "Each Incomplete Pass" },
    3: { abbr: "PY", label: "Passing Yards" },
    4: { abbr: "PTD", label: "TD Pass" },
    15: { abbr: "PTD40", label: "40+ yard TD pass bonus" },
    16: { abbr: "PTD50", label: "50+ yard TD pass bonus" },
    23: { abbr: "RA", label: "Rushing Attempts" },
    24: { abbr: "RY", label: "Rushing Yards" },
    25: { abbr: "RTD", label: "TD Rush" },
    35: { abbr: "RTD40", label: "40+ yard TD rush bonus" },
    36: { abbr: "RTD50", label: "50+ yard TD rush bonus" },
    41: { abbr: "RECS", label: "Receptions" },
    42: { abbr: "REY", label: "Receiving Yards" },
    43: { abbr: "RETD", label: "TD Reception" },
    63: { abbr: "FTD", label: "Fumble Recovered for TD" },
    94: { abbr: "DEFRETTD", label: "Fumble or INT Return for TD" },
    95: { abbr: "INT", label: "Each Interception" },
    99: { abbr: "SK", label: "Each Sack" }
};

module.exports = {
    POSITION_MAP,
    PRO_TEAM_MAP,
    ACTIVITY_MAP,
    PLAYER_STATS_MAP,
    SETTINGS_SCORING_FORMAT_MAP
};
